{ config, pkgs, ..};

{
    # Import other configuration modules
    # (hardware-configuration.nix is autogenerated upon installation)
    # paths in nix expression are always relative the file which defines them
    imports = [
        ./hardware-configuration.nix
        ./my-dev-tools.nix
        ./my-desktop-env.nix
        ./etc.nix
    ];

    # Name your host machine
    networking.hostname = "blizzard";

    # Set your time zone.
    time.timeZone = "America/Detroit";

    # Enter keyboard layout
    service.xserver.layout = "us";
    
    # Define user accoutns
    users.users.bmmoore = {
        extraGroups = ["wheel" "networkmanager" ];
        isNormalUser = true;
    }

    # Install somepackages
    environment.systemPackages = with pkgs; [
        ddate
        testdisk
    ];

    # Enable the OpenSSH daemon
    services.openssh.enable = true;
}
